weather_analytics:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('WAREHOUSE_HOST', 'postgres') }}"
      port: "{{ env_var('WAREHOUSE_PORT', '5432') | int }}"
      user: "{{ env_var('WAREHOUSE_USER', 'warehouse') }}"
      password: "{{ env_var('WAREHOUSE_PASSWORD', 'warehouse') }}"
      dbname: "{{ env_var('WAREHOUSE_DB', 'warehouse') }}"
      schema: analytics
      threads: 4
      keepalives_idle: 0
